services:
  frontend:
    image: binroute-frontend:latest
    container_name: binroute-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3738:3738"
    env_file:
      - .env
    environment:
      NODE_ENV: production
